#Wiki: https://docs.papermc.io/velocity/configuration
config-version = "cv-2.8"

bind = "127.0.0.1:25565"
secret = ""
online-mode = true
player-info-forwarding-mode = "none"
ping-passthrough = "disabled"
force-key-authentication = true
accepts-transfers = false
enable-reuse-port = false
tcp-fast-open = false
haproxy-protocol = false
compression-threshold = 256
compression-level = 6

[servers]
server = "127.0.0.1:25566"
try = ["server"]